### PR TITLE
Insertion Sort Solution

### PR DESCRIPTION
**Pull request by ArshHanjra**

### CODE REVIEW

**Review by Shubhang-2111 — APPROVED** [review]
Your solution has been merged. Thank you for contributing , you can now contribute to other repository of GDSC-CEC.

**Review by Shubhang-2111 — COMMENTED** [review]
This problem has already been contributed. Please try on any other problem.

**Comment by Shubhang-2111** [comment]
You have contributed to multiple projects using single PR. Kindly  make one contribution per PR.
Do the required changes.

**Comment by ShaileshKumar007** [comment]
I'm closing this PR now

**Pull request closed without merging**
