### PR TITLE
completed the code

### PR DESCRIPTION
**Pull request by Sushil-890**
sorting of an array using merge sort is done.
as of the given instructions i wrote the code.

### CODE REVIEW

**Comment by Sushil-890** [comment]
kindly, view my Pull Request
and accept it

**Review by Anamaya1729 — CHANGES_REQUESTED** [review]
Your solution is recursive. Please provide iterative solution for it.

**Comment by Sushil-890** [comment]
ok sir,

**Comment by Shubhang-2111** [comment]
This problem is now already contributed. Thanks for your contribution.

**Pull request closed without merging**
