### PR TITLE
I have done this code

### PR DESCRIPTION
**Pull request by lakshyadeepgogoi**

### CODE REVIEW

**Comment by ShaileshKumar007** [comment]
Thanks for contributing to our project.
Please contribute to one project per PR. You've made multiple changes with 1 PR
Kindly do the changes in your PR and contribute in only a single project with 1 PR

**Comment by lakshyadeepgogoi** [comment]
Ok

**Comment by lakshyadeepgogoi** [comment]
Thanks for responding.
Can you please guide me on how to solve this issue?

**Comment by ShaileshKumar007** [comment]
I've already merged one of your codes. You've successfully made your contribution to this repo.
Please try to make other PRs in different repos of our organization.

Thank You😄

**Pull request closed without merging**
